spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth

server:
  error:
    include-message: always
  port: 8080

socket-server:
  host: 10.80.163.143
  port: 6318